//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        public int PK_Basvuru_Id { get; set; }
        public Nullable<int> Fk_Staj_Id { get; set; }
        public Nullable<int> Fk_Stajyer_Id { get; set; }
        public Nullable<System.DateTime> BasvuruTarihi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Uni_Id { get; set; }
        public Nullable<int> Bolum_Id { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public string Sınıf { get; set; }
        public string YabanciDil { get; set; }
        public string Seviye { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Cv { get; set; }
        public string Resim { get; set; }
        public string BasvuruYazisi { get; set; }
        public Nullable<int> UniNo { get; set; }
        public string BasvuruDurumu { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Stajlar Stajlar { get; set; }
        public virtual STAJYER_TANIM STAJYER_TANIM { get; set; }
        public virtual Uni Uni { get; set; }
    }
}
