//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.GUNLUK_CALISMA = new HashSet<GUNLUK_CALISMA>();
            this.STAJYER_TANIM = new HashSet<STAJYER_TANIM>();
        }
    
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string AdiSoyadi { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string Rol { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string SifreKontrol { get; set; }
        public Nullable<int> CalisanKurumTanim { get; set; }
        public Nullable<int> CalisanDepartman { get; set; }
        public Nullable<int> CalisanPersonel { get; set; }
        public Nullable<bool> rememberme { get; set; }
        public string Kod { get; set; }
        public Nullable<bool> kodOnay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUNLUK_CALISMA> GUNLUK_CALISMA { get; set; }
        public virtual KURUM_DEPARTMAN KURUM_DEPARTMAN { get; set; }
        public virtual KURUM_PERSONEL KURUM_PERSONEL { get; set; }
        public virtual KURUM_TANIM KURUM_TANIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAJYER_TANIM> STAJYER_TANIM { get; set; }
    }
}
