//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURUM_TANIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KURUM_TANIM()
        {
            this.KURUM_DEPARTMAN = new HashSet<KURUM_DEPARTMAN>();
            this.KURUM_PERSONEL = new HashSet<KURUM_PERSONEL>();
            this.Stajlar = new HashSet<Stajlar>();
            this.STAJYER_TANIM = new HashSet<STAJYER_TANIM>();
            this.Kullanicilar = new HashSet<Kullanicilar>();
        }
    
        public int PK_KURUM_TANIM { get; set; }
        public string FIRMA_ADI { get; set; }
        public string FIRMA_YEKTILISI { get; set; }
        public string FIRMA_ADRESİ { get; set; }
        public string TELEFON { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KURUM_DEPARTMAN> KURUM_DEPARTMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KURUM_PERSONEL> KURUM_PERSONEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stajlar> Stajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAJYER_TANIM> STAJYER_TANIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilar { get; set; }
    }
}
