//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajBilgileri
    {
        public int MesajBilgileriId { get; set; }
        public string GönderenMail { get; set; }
        public string AlıcıMail { get; set; }
        public string Konu { get; set; }
        public string MesajIcerigi { get; set; }
        public Nullable<System.DateTime> MesajTarihi { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
    }
}
