//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBYSEntities14 : DbContext
    {
        public SBYSEntities14()
            : base("name=SBYSEntities14")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<GUNLUK_CALISMA> GUNLUK_CALISMA { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KURUM_DEPARTMAN> KURUM_DEPARTMAN { get; set; }
        public virtual DbSet<KURUM_PERSONEL> KURUM_PERSONEL { get; set; }
        public virtual DbSet<KURUM_TANIM> KURUM_TANIM { get; set; }
        public virtual DbSet<MesajBilgileri> MesajBilgileri { get; set; }
        public virtual DbSet<STAJYER_TANIM> STAJYER_TANIM { get; set; }
        public virtual DbSet<Uni> Uni { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
