//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stajlar()
        {
            this.Basvuru = new HashSet<Basvuru>();
            this.STAJYER_TANIM = new HashSet<STAJYER_TANIM>();
        }
    
        public int Pk_Staj_Id { get; set; }
        public int Fk_Kurum_Id { get; set; }
        public int Fk_Kurum_Departman { get; set; }
        public int Staj_Sınıflar { get; set; }
        public System.DateTime Staj_Bas_Tarihi { get; set; }
        public System.DateTime Staj_Bit_Tarihi { get; set; }
        public bool Aktiflik { get; set; }
        public int Fk_Sorumlu_Personel { get; set; }
        public Nullable<int> Fk_Onaylayan_Personel { get; set; }
        public string Baslik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvuru> Basvuru { get; set; }
        public virtual KURUM_DEPARTMAN KURUM_DEPARTMAN { get; set; }
        public virtual KURUM_PERSONEL KURUM_PERSONEL { get; set; }
        public virtual KURUM_PERSONEL KURUM_PERSONEL1 { get; set; }
        public virtual KURUM_TANIM KURUM_TANIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAJYER_TANIM> STAJYER_TANIM { get; set; }
    }
}
