//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAJYER_TANIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAJYER_TANIM()
        {
            this.GUNLUK_CALISMA = new HashSet<GUNLUK_CALISMA>();
        }
    
        public int PK_STAJYER_TANIM { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public Nullable<int> UNIVERSITE { get; set; }
        public string UNIV_NO { get; set; }
        public Nullable<int> BOLUMU { get; set; }
        public string SINIFI { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public int STAJ_YILI { get; set; }
        public Nullable<System.DateTime> STAJ_BAS_TARIHI { get; set; }
        public Nullable<System.DateTime> STAJ_BIT_TARIHI { get; set; }
        public int KURUM_ST_SORUMLUSU { get; set; }
        public int KURUM_ONAY_KISI { get; set; }
        public int FK_STAJ_KURUM { get; set; }
        public int FK_DEPARTMAN { get; set; }
        public Nullable<int> kullaniciId { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUNLUK_CALISMA> GUNLUK_CALISMA { get; set; }
        public virtual KURUM_DEPARTMAN KURUM_DEPARTMAN { get; set; }
        public virtual KURUM_PERSONEL KURUM_PERSONEL { get; set; }
        public virtual KURUM_PERSONEL KURUM_PERSONEL1 { get; set; }
        public virtual KURUM_TANIM KURUM_TANIM { get; set; }
        public virtual Uni Uni { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
