//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajYonetimBilgiSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uni()
        {
            this.Basvuru = new HashSet<Basvuru>();
            this.STAJYER_TANIM = new HashSet<STAJYER_TANIM>();
        }
    
        public int UniId { get; set; }
        public string UniName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvuru> Basvuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAJYER_TANIM> STAJYER_TANIM { get; set; }
    }
}
